webhook:
 url: "YOUR_WEB_HOOK_URL"
 name: "Luxry Webhook Logs"
# Discord Embed Configuration
embed:
 # General Embed Settings
 title: "The system sent a new log message!" # Title of the embed
 description: "%log_here%" # Description of the embed
 color: "#00FF00" # Embed color in HEX format (e.g., #00FF00 for green)

 # Author Section
 author:
  enabled: true # Toggle author section on/off
  name: "Luxry Club" # Author's name
  icon_url: "https://luxry.club/uploads/1730207085508.png" # URL to the author's icon
  url: "https://luxry.club" # URL linked to the author's name

 # Footer Section
 footer:
  enabled: true # Toggle footer section on/off
  text: "Powered by Luxry Club" # Footer text
  icon_url: "https://luxry.club/uploads/1730207085508.png" # URL to the footer icon

 # Thumbnail
 thumbnail:
  enabled: true # Toggle thumbnail on/off
  url: "https://luxry.club/uploads/1730207085508.png" # URL to the thumbnail image

 # Image
 image:
  enabled: true # Toggle image on/off
  url: "https://luxry.club/uploads/1730207085508.png" # URL to the main image

 # Timestamp
 timestamp:
  enabled: true # Toggle timestamp on/off
  use_current_time: true # Use the current time for the timestamp (true/false)